package com.example.td5

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class ContactActivity : AppCompatActivity() {
    val contacts: ArrayList<Contact> = ArrayList()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_contact)
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Lavie","Antonin","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Lavie","Antonin","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))
        contacts.add(Contact("Duvivier","Clément","https://gal.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Fgal.2Fvar.2Fgal.2Fstorage.2Fimages.2Fmedia.2Fmultiupload_du_07_decembre_2013.2Fjean-pierre-foucault_leader.2F2307250-1-fre-FR.2Fjean-pierre-foucault_leader.2Ejpg/480x480/quality/80/jean-pierre-foucault-son-engagement-politique-fait-debat.jpg"))

        var rvContacts: RecyclerView = findViewById(R.id.rvContacts)
        rvContacts.adapter = ContactsAdapter(contacts,this)
        rvContacts.layoutManager = LinearLayoutManager(this)
    }
}